AllCops:
  # Include common Ruby source files.
  Exclude:
    - '**/vendor/**/*'
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'

Metrics/LineLength:
  Max: 110

Metrics/AbcSize:
  Max: 21

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 15
