---
- hosts: buildernodes
  remote_user: pi
  become: yes
  become_method: sudo
  tasks:
    - file: 
        path: /tmp/ramdisk
        state: absent
    - file: 
        path: /tmp/ramdisk
        state: directory
        mode: 0755
    - name: create the ramdisk file
      shell: mkinitramfs -o /tmp/ramdisk/cattlekernel.img
    - name: bring in the rest of boot
      shell: /bin/cp -R /boot/* /tmp/ramdisk/
    - name: remove the old kernel
      shell: rm -rf /tmp/ramdisk/kernel*img