---
- hosts: buildernodes
  remote_user: pi
  become: yes
  become_method: sudo
  tasks:
    - name: install packages 
      apt: 
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items: 
        - vim 
        - initramfs-tools
        - squashfs-tools
        - unionfs-fuse
        - ufw
    - name: disable swap
      command: dphys-swapfile swapoff
    - name: disable swap - make sure if does not come back
      command: dphys-swapfile uninstall
    - name: upgrade packages and dist
      apt:
        upgrade: full