---
- hosts: buildernodes
  remote_user: pi
  become: yes
  become_method: sudo
  tasks:
    - name: sentinel start
      command: echo start
    - import_tasks: tasks/update_software.yml
    - import_tasks: tasks/reboot_and_wait.yml
    - name: sentinel done
      command: echo done